### ISSUE TITLE
希望能删除某一行

### ISSUE THREAD

**Issue by Khaos116** [shinehanx/CuteSqlite#2]
有些垃圾数据，想删除某一行，折腾半天没找到怎么删除

**Comment by shinehanx** [comment]
![1729776578906](https://github.com/user-attachments/assets/0bd67d3c-6acb-49a6-ada3-3a5017832205)

**Comment by shinehanx** [comment]
之前单击一行后，删除按钮未亮，这个BUG在v0.2.1可以修复，感谢你的反馈：）
